### ISSUE TITLE
FeatureRequest: SearsCatalog Controllersupport for scrolling

### ISSUE THREAD

**Issue by JamDaBam** [mu-arch/ComfyMods#10]
Hi, While the mod works great with mouse and keyboard, it unfortunately lacks support for scrolling with a controller.
I would have imagined that you could scroll within the build menus with the right stick.

The workaround of enlarging the grid doesn't work either, as there seems to be a general limit of the grid from the game.

![gridbounds](https://user-images.githubusercontent.com/46002896/218568360-bcc807ac-b49b-490e-8b42-c3c8af106879.gif)

Thanks btw for your awesome modcollection.

**Comment by redseiko** [comment]
I can't mark this as closed (as this is the parent repo for my fork) but I've added controller support as of version 1.1.0 on Thunderstore.

https://valheim.thunderstore.io/package/ComfyMods/SearsCatalog/

I only tested the piece selection movement using the methods the controller would eventually call so lemme know how it goes.

**Comment by JamDaBam** [comment]
@redseiko 
I have tested it.
Now it automatically scrolls to the next row when you get to the bottom.

Thank you so much for your effort.

(If this issueis set to "open" again, it can be closed again.)
